%include "macros/patch.inc"
%include "macros/imports.inc"

cextern _imp__LoadLibraryA
cextern _imp__GetProcAddress


%macro importlist 1
    %1_library kernel32
    %1_import GetPrivateProfileStringA
    %1_import GetPrivateProfileIntA
    
    %1_library msvcrt
    %1_import $I10_OUTPUT
    %1_import ??0__non_rtti_object@@QAE@ABV0@@Z
    %1_import ??0__non_rtti_object@@QAE@PBD@Z
    %1_import ??0bad_cast@@AAE@PBQBD@Z
    %1_import ??0bad_cast@@QAE@ABV0@@Z
    %1_import ??0bad_cast@@QAE@PBD@Z
    %1_import ??0bad_typeid@@QAE@ABV0@@Z
    %1_import ??0bad_typeid@@QAE@PBD@Z
    %1_import ??0exception@@QAE@ABQBD@Z
    %1_import ??0exception@@QAE@ABV0@@Z
    %1_import ??0exception@@QAE@XZ
    %1_import ??1__non_rtti_object@@UAE@XZ
    %1_import ??1bad_cast@@UAE@XZ
    %1_import ??1exception@@UAE@XZ
    %1_import ??1type_info@@UAE@XZ
    %1_import ??2@YAPAXI@Z
    %1_import ??3@YAXPAX@Z
    %1_import ??4__non_rtti_object@@QAEAAV0@ABV0@@Z
    %1_import ??4exception@@QAEAAV0@ABV0@@Z
    %1_import ??8type_info@@QBEHABV0@@Z
    %1_import ??9type_info@@QBEHABV0@@Z
    %1_import ??_7__non_rtti_object@@6B@
    %1_import ??_7bad_cast@@6B@
    %1_import ??_7bad_typeid@@6B@
    %1_import ??_7exception@@6B@
    %1_import ??_E__non_rtti_object@@UAEPAXI@Z
    %1_import ??_Ebad_cast@@UAEPAXI@Z
    %1_import ??_Eexception@@UAEPAXI@Z
    %1_import ??_Fbad_cast@@QAEXXZ
    %1_import ??_Fbad_typeid@@QAEXXZ
    %1_import ??_G__non_rtti_object@@UAEPAXI@Z
    %1_import ??_Gbad_cast@@UAEPAXI@Z
    %1_import ??_Gexception@@UAEPAXI@Z
    %1_import ??_U@YAPAXI@Z
    %1_import ??_V@YAXPAX@Z
    %1_import ?_query_new_handler@@YAP6AHI@ZXZ
    %1_import ?_query_new_mode@@YAHXZ
    %1_import ?_set_new_handler@@YAP6AHI@ZP6AHI@Z@Z
    %1_import ?_set_new_mode@@YAHH@Z
    %1_import ?_set_se_translator@@YAP6AXIPAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z
    %1_import ?before@type_info@@QBEHABV1@@Z
    %1_import ?name@type_info@@QBEPBDXZ
    %1_import ?raw_name@type_info@@QBEPBDXZ
    %1_import ?set_new_handler@@YAP6AXXZP6AXXZ@Z
    %1_import ?set_terminate@@YAP6AXXZP6AXXZ@Z
    %1_import ?set_unexpected@@YAP6AXXZP6AXXZ@Z
    %1_import ?terminate@@YAXXZ
    %1_import ?unexpected@@YAXXZ
    %1_import ?what@exception@@UBEPBDXZ
    %1_import ___lc_codepage_func
    %1_import ___lc_handle_func
    %1_import ___mb_cur_max_func
    %1_import ___setlc_active_func
    %1_import ___unguarded_readlc_active_add_func
    %1_import __argc
    %1_import __argv
    %1_import __badioinfo
    %1_import __crtCompareStringA
    %1_import __crtCompareStringW
    %1_import __crtGetLocaleInfoW
    %1_import __crtGetStringTypeW
    %1_import __crtLCMapStringA
    %1_import __crtLCMapStringW
    %1_import __CxxCallUnwindDtor
    %1_import __CxxDetectRethrow
    %1_import __CxxExceptionFilter
    %1_import __CxxFrameHandler
    %1_import __CxxLongjmpUnwind
    %1_import __CxxQueryExceptionSize
    %1_import __CxxRegisterExceptionObject
    %1_import __CxxUnregisterExceptionObject
    %1_import __DestructExceptionObject
    %1_import __dllonexit
    %1_import __doserrno
    %1_import __fpecode
    %1_import __getmainargs
    %1_import __initenv
    %1_import __iob_func
    %1_import __isascii
    %1_import __iscsym
    %1_import __iscsymf
    %1_import __lc_codepage
    %1_import __lc_collate_cp
    %1_import __lc_handle
    %1_import __lconv_init
    %1_import __mb_cur_max
    %1_import __p___argc
    %1_import __p___argv
    %1_import __p___initenv
    %1_import __p___mb_cur_max
    %1_import __p___wargv
    %1_import __p___winitenv
    %1_import __p__acmdln
    %1_import __p__amblksiz
    %1_import __p__commode
    %1_import __p__daylight
    %1_import __p__dstbias
    %1_import __p__environ
    %1_import __p__fileinfo
    %1_import __p__fmode
    %1_import __p__mbcasemap
    %1_import __p__mbctype
    %1_import __p__osver
    %1_import __p__pctype
    %1_import __p__pgmptr
    %1_import __p__pwctype
    %1_import __p__timezone
    %1_import __p__tzname
    %1_import __p__wcmdln
    %1_import __p__wenviron
    %1_import __p__winmajor
    %1_import __p__winminor
    %1_import __p__winver
    %1_import __p__wpgmptr
    %1_import __pctype_func
    %1_import __pioinfo
    %1_import __pxcptinfoptrs
    %1_import __RTCastToVoid
    %1_import __RTDynamicCast
    %1_import __RTtypeid
    %1_import __set_app_type
    %1_import __setlc_active
    %1_import __setusermatherr
    %1_import __STRINGTOLD
    %1_import __threadhandle
    %1_import __threadid
    %1_import __toascii
    %1_import __uncaught_exception
    %1_import __unDName
    %1_import __unDNameEx
    %1_import __unguarded_readlc_active
    %1_import __wargv
    %1_import __wcserror
    %1_import __wgetmainargs
    %1_import __winitenv
    %1_import _abnormal_termination
    %1_import _access
    %1_import _acmdln
    %1_import _adj_fdiv_m16i
    %1_import _adj_fdiv_m32
    %1_import _adj_fdiv_m32i
    %1_import _adj_fdiv_m64
    %1_import _adj_fdiv_r
    %1_import _adj_fdivr_m16i
    %1_import _adj_fdivr_m32
    %1_import _adj_fdivr_m32i
    %1_import _adj_fdivr_m64
    %1_import _adj_fpatan
    %1_import _adj_fprem
    %1_import _adj_fprem1
    %1_import _adj_fptan
    %1_import _adjust_fdiv
    %1_import _aexit_rtn
    %1_import _aligned_free
    %1_import _aligned_malloc
    %1_import _aligned_offset_malloc
    %1_import _aligned_offset_realloc
    %1_import _aligned_realloc
    %1_import _amsg_exit
    %1_import _assert
    %1_import _atodbl
    %1_import _atoi64
    %1_import _atoldbl
    %1_import _beep
    %1_import _beginthread
    %1_import _beginthreadex
    %1_import _c_exit
    %1_import _cabs
    %1_import _callnewh
    %1_import _cexit
    %1_import _cgets
    %1_import _cgetws
    %1_import _chdir
    %1_import _chdrive
    %1_import _chgsign
    %1_import _chkesp
    %1_import _chmod
    %1_import _chsize
    %1_import _CIacos
    %1_import _CIasin
    %1_import _CIatan
    %1_import _CIatan2
    %1_import _CIcos
    %1_import _CIcosh
    %1_import _CIexp
    %1_import _CIfmod
    %1_import _CIlog
    %1_import _CIlog10
    %1_import _CIpow
    %1_import _CIsin
    %1_import _CIsinh
    %1_import _CIsqrt
    %1_import _CItan
    %1_import _CItanh
    %1_import _clearfp
    %1_import _close
    %1_import _commit
    %1_import _commode
    %1_import _control87
    %1_import _controlfp
    %1_import _copysign
    %1_import _cprintf
    %1_import _cputs
    %1_import _cputws
    %1_import _creat
    %1_import _cscanf
    %1_import _ctime64
    %1_import _ctype
    %1_import _cwait
    %1_import _cwprintf
    %1_import _cwscanf
    %1_import _CxxThrowException
    %1_import _daylight
    %1_import _dstbias
    %1_import _dup
    %1_import _dup2
    %1_import _ecvt
    %1_import _EH_prolog
    %1_import _endthread
    %1_import _endthreadex
    %1_import _environ
    %1_import _eof
    %1_import _errno
    %1_import _except_handler2
    %1_import _except_handler3
    %1_import _execl
    %1_import _execle
    %1_import _execlp
    %1_import _execlpe
    %1_import _execv
    %1_import _execve
    %1_import _execvp
    %1_import _execvpe
    %1_import _exit
    %1_import _expand
    %1_import _fcloseall
    %1_import _fcvt
    %1_import _fdopen
    %1_import _fgetchar
    %1_import _fgetwchar
    %1_import _filbuf
    %1_import _fileinfo
    %1_import _filelength
    %1_import _filelengthi64
    %1_import _fileno
    %1_import _findclose
    %1_import _findfirst
    %1_import _findfirst64
    %1_import _findfirsti64
    %1_import _findnext
    %1_import _findnext64
    %1_import _findnexti64
    %1_import _finite
    %1_import _flsbuf
    %1_import _flushall
    %1_import _fmode
    %1_import _fpclass
    %1_import _fpieee_flt
    %1_import _fpreset
    %1_import _fputchar
    %1_import _fputwchar
    %1_import _fsopen
    %1_import _fstat
    %1_import _fstat64
    %1_import _fstati64
    %1_import _ftime
    %1_import _ftime64
    %1_import _ftol
    %1_import _fullpath
    %1_import _futime
    %1_import _futime64
    %1_import _gcvt
    %1_import _get_osfhandle
    %1_import _get_sbh_threshold
    %1_import _getch
    %1_import _getche
    %1_import _getcwd
    %1_import _Getdays
    %1_import _getdcwd
    %1_import _getdiskfree
    %1_import _getdllprocaddr
    %1_import _getdrive
    %1_import _getdrives
    %1_import _getmaxstdio
    %1_import _getmbcp
    %1_import _Getmonths
    %1_import _getpid
    %1_import _getsystime
    %1_import _Gettnames
    %1_import _getw
    %1_import _getwch
    %1_import _getwche
    %1_import _getws
    %1_import _global_unwind2
    %1_import _gmtime64
    %1_import _heapadd
    %1_import _heapchk
    %1_import _heapmin
    %1_import _heapset
    %1_import _heapused
    %1_import _heapwalk
    %1_import _HUGE
    %1_import _hypot
    %1_import _i64toa
    %1_import _i64tow
    %1_import _initterm
    %1_import _inp
    %1_import _inpd
    %1_import _inpw
    %1_import _iob
    %1_import _isatty
    %1_import _isctype
    %1_import _ismbbalnum
    %1_import _ismbbalpha
    %1_import _ismbbgraph
    %1_import _ismbbkalnum
    %1_import _ismbbkana
    %1_import _ismbbkprint
    %1_import _ismbbkpunct
    %1_import _ismbblead
    %1_import _ismbbprint
    %1_import _ismbbpunct
    %1_import _ismbbtrail
    %1_import _ismbcalnum
    %1_import _ismbcalpha
    %1_import _ismbcdigit
    %1_import _ismbcgraph
    %1_import _ismbchira
    %1_import _ismbckata
    %1_import _ismbcl0
    %1_import _ismbcl1
    %1_import _ismbcl2
    %1_import _ismbclegal
    %1_import _ismbclower
    %1_import _ismbcprint
    %1_import _ismbcpunct
    %1_import _ismbcspace
    %1_import _ismbcsymbol
    %1_import _ismbcupper
    %1_import _ismbslead
    %1_import _ismbstrail
    %1_import _isnan
    %1_import _itoa
    %1_import _itow
    %1_import _j0
    %1_import _j1
    %1_import _jn
    %1_import _kbhit
    %1_import _lfind
    %1_import _loaddll
    %1_import _local_unwind2
    %1_import _localtime64
    %1_import _lock
    %1_import _locking
    %1_import _logb
    %1_import _longjmpex
    %1_import _lrotl
    %1_import _lrotr
    %1_import _lsearch
    %1_import _lseek
    %1_import _lseeki64
    %1_import _ltoa
    %1_import _ltow
    %1_import _makepath
    %1_import _mbbtombc
    %1_import _mbbtype
    %1_import _mbcasemap
    %1_import _mbccpy
    %1_import _mbcjistojms
    %1_import _mbcjmstojis
    %1_import _mbclen
    %1_import _mbctohira
    %1_import _mbctokata
    %1_import _mbctolower
    %1_import _mbctombb
    %1_import _mbctoupper
    %1_import _mbctype
    %1_import _mbsbtype
    %1_import _mbscat
    %1_import _mbschr
    %1_import _mbscmp
    %1_import _mbscoll
    %1_import _mbscpy
    %1_import _mbscspn
    %1_import _mbsdec
    %1_import _mbsdup
    %1_import _mbsicmp
    %1_import _mbsicoll
    %1_import _mbsinc
    %1_import _mbslen
    %1_import _mbslwr
    %1_import _mbsnbcat
    %1_import _mbsnbcmp
    %1_import _mbsnbcnt
    %1_import _mbsnbcoll
    %1_import _mbsnbcpy
    %1_import _mbsnbicmp
    %1_import _mbsnbicoll
    %1_import _mbsnbset
    %1_import _mbsncat
    %1_import _mbsnccnt
    %1_import _mbsncmp
    %1_import _mbsncoll
    %1_import _mbsncpy
    %1_import _mbsnextc
    %1_import _mbsnicmp
    %1_import _mbsnicoll
    %1_import _mbsninc
    %1_import _mbsnset
    %1_import _mbspbrk
    %1_import _mbsrchr
    %1_import _mbsrev
    %1_import _mbsset
    %1_import _mbsspn
    %1_import _mbsspnp
    %1_import _mbsstr
    %1_import _mbstok
    %1_import _mbstrlen
    %1_import _mbsupr
    %1_import _memccpy
    %1_import _memicmp
    %1_import _mkdir
    %1_import _mktemp
    %1_import _mktime64
    %1_import _msize
    %1_import _nextafter
    %1_import _onexit
    %1_import _open
    %1_import _open_osfhandle
    %1_import _osplatform
    %1_import _osver
    %1_import _outp
    %1_import _outpd
    %1_import _outpw
    %1_import _pclose
    %1_import _pctype
    %1_import _pgmptr
    %1_import _pipe
    %1_import _popen
    %1_import _purecall
    %1_import _putch
    %1_import _putenv
    %1_import _putw
    %1_import _putwch
    %1_import _putws
    %1_import _pwctype
    %1_import _read
    %1_import _resetstkoflw
    %1_import _rmdir
    %1_import _rmtmp
    %1_import _safe_fdiv
    %1_import _safe_fdivr
    %1_import _safe_fprem
    %1_import _safe_fprem1
    %1_import _scalb
    %1_import _scprintf
    %1_import _scwprintf
    %1_import _searchenv
    %1_import _seh_longjmp_unwind
    %1_import _set_error_mode
    %1_import _set_sbh_threshold
    %1_import _set_SSE2_enable
    %1_import _seterrormode
    %1_import _setjmp
    %1_import _setjmp3
    %1_import _setmaxstdio
    %1_import _setmbcp
    %1_import _setmode
    %1_import _setsystime
    %1_import _sleep
    %1_import _snprintf
    %1_import _snscanf
    %1_import _snwprintf
    %1_import _snwscanf
    %1_import _sopen
    %1_import _spawnl
    %1_import _spawnle
    %1_import _spawnlp
    %1_import _spawnlpe
    %1_import _spawnv
    %1_import _spawnve
    %1_import _spawnvp
    %1_import _spawnvpe
    %1_import _splitpath
    %1_import _stat
    %1_import _stat64
    %1_import _stati64
    %1_import _statusfp
    %1_import _strcmpi
    %1_import _strdate
    %1_import _strerror
    %1_import _Strftime
    %1_import _stricoll
    %1_import _strlwr
    %1_import _strncoll
    %1_import _strnicmp
    %1_import _strnicoll
    %1_import _strnset
    %1_import _strrev
    %1_import _strset
    %1_import _strtime
    %1_import _strtoi64
    %1_import _strtoui64
    %1_import _strupr
    %1_import _swab
    %1_import _sys_errlist
    %1_import _sys_nerr
    %1_import _tell
    %1_import _telli64
    %1_import _tempnam
    %1_import _time64
    %1_import _timezone
    %1_import _tolower
    %1_import _toupper
    %1_import _tzname
    %1_import _tzset
    %1_import _ui64toa
    %1_import _ui64tow
    %1_import _ultoa
    %1_import _ultow
    %1_import _umask
    %1_import _ungetch
    %1_import _ungetwch
    %1_import _unlink
    %1_import _unloaddll
    %1_import _unlock
    %1_import _utime
    %1_import _utime64
    %1_import _vscprintf
    %1_import _vscwprintf
    %1_import _vsnprintf
    %1_import _vsnwprintf
    %1_import _waccess
    %1_import _wasctime
    %1_import _wchdir
    %1_import _wchmod
    %1_import _wcmdln
    %1_import _wcreat
    %1_import _wcsdup
    %1_import _wcserror
    %1_import _wcsicmp
    %1_import _wcsicoll
    %1_import _wcslwr
    %1_import _wcsncoll
    %1_import _wcsnicmp
    %1_import _wcsnicoll
    %1_import _wcsnset
    %1_import _wcsrev
    %1_import _wcsset
    %1_import _wcstoi64
    %1_import _wcstoui64
    %1_import _wcsupr
    %1_import _wctime
    %1_import _wctime64
    %1_import _wenviron
    %1_import _wexecl
    %1_import _wexecle
    %1_import _wexeclp
    %1_import _wexeclpe
    %1_import _wexecv
    %1_import _wexecve
    %1_import _wexecvp
    %1_import _wexecvpe
    %1_import _wfdopen
    %1_import _wfindfirst
    %1_import _wfindfirst64
    %1_import _wfindfirsti64
    %1_import _wfindnext
    %1_import _wfindnext64
    %1_import _wfindnexti64
    %1_import _wfopen
    %1_import _wfreopen
    %1_import _wfsopen
    %1_import _wfullpath
    %1_import _wgetcwd
    %1_import _wgetdcwd
    %1_import _wgetenv
    %1_import _winmajor
    %1_import _winminor
    %1_import _winver
    %1_import _wmakepath
    %1_import _wmkdir
    %1_import _wmktemp
    %1_import _wopen
    %1_import _wperror
    %1_import _wpgmptr
    %1_import _wpopen
    %1_import _wputenv
    %1_import _wremove
    %1_import _wrename
    %1_import _write
    %1_import _wrmdir
    %1_import _wsearchenv
    %1_import _wsetlocale
    %1_import _wsopen
    %1_import _wspawnl
    %1_import _wspawnle
    %1_import _wspawnlp
    %1_import _wspawnlpe
    %1_import _wspawnv
    %1_import _wspawnve
    %1_import _wspawnvp
    %1_import _wspawnvpe
    %1_import _wsplitpath
    %1_import _wstat
    %1_import _wstat64
    %1_import _wstati64
    %1_import _wstrdate
    %1_import _wstrtime
    %1_import _wsystem
    %1_import _wtempnam
    %1_import _wtmpnam
    %1_import _wtof
    %1_import _wtoi
    %1_import _wtoi64
    %1_import _wtol
    %1_import _wunlink
    %1_import _wutime
    %1_import _wutime64
    %1_import _XcptFilter
    %1_import _y0
    %1_import _y1
    %1_import _yn
    %1_import abort
    %1_import abs
    %1_import acos
    %1_import asctime
    %1_import asin
    %1_import atan
    %1_import atan2
    %1_import atexit
    %1_import atof
    %1_import atoi
    %1_import atol
    %1_import bsearch
    %1_import calloc
    %1_import ceil
    %1_import clearerr
    %1_import clock
    %1_import cos
    %1_import cosh
    %1_import ctime
    %1_import difftime
    %1_import div
    %1_import entry
    %1_import exit
    %1_import exp
    %1_import fabs
    %1_import fclose
    %1_import feof
    %1_import ferror
    %1_import fflush
    %1_import fgetc
    %1_import fgetpos
    %1_import fgets
    %1_import fgetwc
    %1_import fgetws
    %1_import floor
    %1_import fmod
    %1_import fopen
    %1_import fprintf
    %1_import fputc
    %1_import fputs
    %1_import fputwc
    %1_import fputws
    %1_import fread
    %1_import free
    %1_import freopen
    %1_import frexp
    %1_import fscanf
    %1_import fseek
    %1_import fsetpos
    %1_import ftell
    %1_import fwprintf
    %1_import fwrite
    %1_import fwscanf
    %1_import getchar
    %1_import getenv
    %1_import gets
    %1_import getwc
    %1_import getwchar
    %1_import gmtime
    %1_import is_wctype
    %1_import isalnum
    %1_import isalpha
    %1_import iscntrl
    %1_import isdigit
    %1_import isgraph
    %1_import isleadbyte
    %1_import islower
    %1_import isprint
    %1_import ispunct
    %1_import isspace
    %1_import isupper
    %1_import iswalnum
    %1_import iswalpha
    %1_import iswascii
    %1_import iswcntrl
    %1_import iswctype
    %1_import iswdigit
    %1_import iswgraph
    %1_import iswlower
    %1_import iswprint
    %1_import iswpunct
    %1_import iswspace
    %1_import iswupper
    %1_import iswxdigit
    %1_import isxdigit
    %1_import ldexp
    %1_import localeconv
    %1_import localtime
    %1_import log
    %1_import log10
    %1_import longjmp
    %1_import malloc
    %1_import mblen
    %1_import mbstowcs
    %1_import mbtowc
    %1_import memchr
    %1_import memcmp
    %1_import memcpy
    %1_import memmove
    %1_import memset
    %1_import mktime
    %1_import modf
    %1_import perror
    %1_import pow
    %1_import printf
    %1_import putchar
    %1_import puts
    %1_import putwc
    %1_import putwchar
    %1_import qsort
    %1_import raise
    %1_import rand
    %1_import realloc
    %1_import remove
    %1_import rename
    %1_import rewind
    %1_import scanf
    %1_import setbuf
    %1_import setlocale
    %1_import setvbuf
    %1_import signal
    %1_import sin
    %1_import sinh
    %1_import sprintf
    %1_import sqrt
    %1_import srand
    %1_import sscanf
    %1_import strchr
    %1_import strcmp
    %1_import strcoll
    %1_import strcspn
    %1_import strerror
    %1_import strftime
    %1_import strlen
    %1_import strncat
    %1_import strncmp
    %1_import strncpy
    %1_import strpbrk
    %1_import strrchr
    %1_import strspn
    %1_import strstr
    %1_import strtod
    %1_import strtok
    %1_import strtol
    %1_import strtoul
    %1_import strxfrm
    %1_import swprintf
    %1_import swscanf
    %1_import system
    %1_import tan
    %1_import tanh
    %1_import time
    %1_import tmpfile
    %1_import tmpnam
    %1_import tolower
    %1_import toupper
    %1_import towlower
    %1_import towupper
    %1_import ungetc
    %1_import ungetwc
    %1_import vfprintf
    %1_import vfwprintf
    %1_import vprintf
    %1_import vsprintf
    %1_import vswprintf
    %1_import vwprintf
    %1_import wcscat
    %1_import wcschr
    %1_import wcscmp
    %1_import wcscoll
    %1_import wcscpy
    %1_import wcscspn
    %1_import wcsftime
    %1_import wcslen
    %1_import wcsncat
    %1_import wcsncmp
    %1_import wcsncpy
    %1_import wcspbrk
    %1_import wcsrchr
    %1_import wcsspn
    %1_import wcsstr
    %1_import wcstod
    %1_import wcstok
    %1_import wcstol
    %1_import wcstombs
    %1_import wcstoul
    %1_import wcsxfrm
    %1_import wctomb
    %1_import wprintf
    %1_import wscanf
%endmacro


importlist define

gfunction imports_init
    pushad
    importlist load
    popad
    retn
